#!/usr/bin/env python3
"""Generate NFC tables + a cross-check corpus for the zig tokenizer port.

Outputs (into ../zig/src/ and ../zig/):
  nfc_tables.zig   canonical decomposition map, nonzero ccc map, and the
                   composition table — the composition table is BEHAVIOR-
                   DERIVED: for every canonical 2-part decomposition (a,b)
                   we ask Python's own NFC whether a+b recomposes, and store
                   its answer. This sidesteps the composition-exclusion lists
                   entirely and guarantees agreement with this Python's
                   unicode version on pair composition.
  nfc_corpus.json   [{raw, nfc}] cross-check pairs: every codepoint whose NFC
                   differs from itself, canonical-combining sequences, Hangul
                   jamo compositions/syllables, plus the tokenizer spike's
                   probes. Run both sides and compare.

Hangul syllable composition/decomposition is algorithmic (handled in zig,
excluded from tables). Python 3.10 = Unicode 14.0 — recorded in the output;
NFC is extremely stable across versions, and the corpus is the real gate.
"""

import json
import pathlib
import unicodedata

OUT = pathlib.Path(__file__).resolve().parent / "zig" / "src" / "nfc_tables.zig"
CORPUS = pathlib.Path(__file__).resolve().parent / "zig" / "nfc_corpus.json"


def main() -> None:
    version = unicodedata.unidata_version

    # --- canonical decomposition (no <compat>/<font>/... tag prefix) --------
    decomp: dict[int, list[int]] = {}
    for cp in range(0x110000):
        if 0xAC00 <= cp <= 0xD7A3:
            continue  # Hangul syllables: algorithmic in zig
        d = unicodedata.decomposition(chr(cp))
        if d and not d.startswith("<"):
            decomp[cp] = [int(x, 16) for x in d.split()]

    # --- nonzero canonical combining class ---------------------------------
    ccc = {
        cp: c
        for cp in range(0x110000)
        if (c := unicodedata.combining(chr(cp))) != 0
    }

    # --- composition table, behavior-derived from Python's NFC -------------
    comp: dict[tuple[int, int], int] = {}
    for cp, parts in sorted(decomp.items()):
        if len(parts) != 2:
            continue
        a, b = parts
        got = unicodedata.normalize("NFC", chr(a) + chr(b))
        if len(got) == 1:
            comp[(a, b)] = ord(got)
    # sanity: every composition target should be a real recomposition
    assert all(unicodedata.normalize("NFC", chr(a) + chr(b)) == chr(x)
               for (a, b), x in comp.items())

    # --- emit zig ----------------------------------------------------------
    def u21_list(items, per_line=12):
        lines, row = [], []
        for it in items:
            row.append(f"0x{it:04X}")
            if len(row) == per_line:
                lines.append("    " + ", ".join(row) + ",")
                row = []
        if row:
            lines.append("    " + ", ".join(row) + ",")
        return "\n".join(lines)

    keys = sorted(decomp)
    flat: list[int] = []
    offs: list[int] = []
    for cp in keys:
        offs.append(len(flat))
        flat.extend(decomp[cp])
    offs.append(len(flat))

    ccc_keys = sorted(ccc)
    comp_keys = sorted(comp)

    zig = f"""//! Generated by training/../make_nfc_tables.py — DO NOT EDIT BY HAND.
//! Unicode {version} (Python unicodedata); canonical decomposition + nonzero
//! ccc + behavior-derived composition pairs. Hangul is algorithmic (nfc.zig).
pub const UNICODE_VERSION = "{version}";

/// Sorted codepoints with a canonical (untagged) direct decomposition.
pub const decomp_cp: []const u21 = &.{{ {u21_list(keys, 10)} }};
/// Offsets into `decomp_flat`; length = decomp_cp.len + 1.
pub const decomp_off: []const u16 = &.{{ {u21_list(offs, 12)} }};
/// Flat decomposition targets.
pub const decomp_flat: []const u21 = &.{{ {u21_list(flat, 12)} }};

/// Sorted codepoints with a nonzero canonical combining class.
pub const ccc_cp: []const u21 = &.{{ {u21_list(ccc_keys, 10)} }};
pub const ccc_val: []const u8 = &.{{ {u21_list(ccc.values(), 12)} }};

/// Sorted (a, b) -> x composition pairs, behavior-derived from Python's NFC.
pub const comp_a: []const u21 = &.{{ {u21_list([k[0] for k in comp_keys], 10)} }};
pub const comp_b: []const u21 = &.{{ {u21_list([k[1] for k in comp_keys], 10)} }};
pub const comp_x: []const u21 = &.{{ {u21_list([comp[k] for k in comp_keys], 10)} }};
"""
    OUT.write_text(zig)

    # --- corpus ------------------------------------------------------------
    raw: set[str] = set()
    for cp in range(0x110000):
        ch = chr(cp)
        if unicodedata.normalize("NFC", ch) != ch:
            raw.add(ch)
    # combining sequences: base + every nonzero-ccc mark (representative sweep)
    marks = sorted(ccc)
    for base in (0x0061, 0x0041, 0x03B1, 0x0430, 0x0915):  # a, A, α, а, क
        for m in marks[:200]:
            raw_seq = chr(base) + chr(m)
            raw.add(raw_seq)
    # double/triple marks (ordering), precomposed/decomposed twins
    for m1, m2 in ((0x0301, 0x0302), (0x0302, 0x0301), (0x0301, 0x0327),
                   (0x0327, 0x0301), (0x0316, 0x0301), (0x0301, 0x0316)):
        raw.add("a" + chr(m1) + chr(m2))
    # Hangul: L+V, LV+T, L+V+T, T alone after consonant
    for seq in ("가", "각", "각ᆨ", "ᄀᆨ", "ᅡ", "ᆨ", "각"):
        raw.add(seq)
    # tokenizer spike probes
    for s in ("café decomposed: café", "é", "Å", "A◌̧"):
        raw.add(s)

    corpus = []
    for s in sorted(raw, key=lambda x: (len(x), x)):
        corpus.append({"raw": s, "nfc": unicodedata.normalize("NFC", s)})
    CORPUS.write_text(json.dumps(corpus, ensure_ascii=False, indent=0))

    changed = sum(1 for c in corpus if c["raw"] != c["nfc"])
    print(f"unicode {version}")
    print(f"tables -> {OUT}  (decomp={len(keys)} ccc={len(ccc)} comp={len(comp)})")
    print(f"corpus -> {CORPUS}  ({len(corpus)} entries, {changed} change under NFC)")


if __name__ == "__main__":
    main()
