#!/usr/bin/env python3
"""Generate complete Unicode character-class tables for the zig tokenizer port.

Replaces the spike's curated ranges with FULL UCD data from Python's
`unicodedata.category`:
  isL  -> categories L*        (matches Rust regex / fancy-regex `\p{L}`)
  isN  -> categories N*        (Nd+Nl+No — matches `\p{N}`; the curated table
                                only had Nd subsets, so e.g. ½ was misclassified)
  isWs -> the Unicode White_Space property (explicit list; NOT Python's
          str.isspace, which also counts \\x1c-\\x1f that Rust \\s excludes)

Ranges are merged runs, sorted, emitted as `.{ lo, hi }` inclusive pairs —
lookups early-exit linearly (fine for spike-scale strings).
"""

import pathlib
import unicodedata

OUT = pathlib.Path(__file__).resolve().parent / "zig" / "src" / "class_tables.zig"

# Unicode White_Space property (what Rust regex \s means).
WHITE_SPACE = (
    [(0x09, 0x0D), (0x20, 0x20), (0x85, 0x85), (0xA0, 0xA0), (0x1680, 0x1680)]
    + [(0x2000, 0x200A)]
    + [(0x2028, 0x2029), (0x202F, 0x202F), (0x205F, 0x205F), (0x3000, 0x3000)]
)


def collect(pred) -> list[tuple[int, int]]:
    runs: list[tuple[int, int]] = []
    for cp in range(0x110000):
        if not pred(cp):
            continue
        if runs and runs[-1][1] + 1 == cp:
            lo, _ = runs[-1]
            runs[-1] = (lo, cp)
        else:
            runs.append((cp, cp))
    return runs


def main() -> None:
    version = unicodedata.unidata_version

    def is_l(cp: int) -> bool:
        return unicodedata.category(chr(cp)).startswith("L")

    def is_n(cp: int) -> bool:
        return unicodedata.category(chr(cp)).startswith("N")

    l_runs = collect(is_l)
    n_runs = collect(is_n)
    ws_runs = collect(lambda cp: any(lo <= cp <= hi for lo, hi in WHITE_SPACE))
    # sanity: merged ranges == the exact White_Space set (25 codepoints)
    expected_ws = {
        0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20, 0x85, 0xA0, 0x1680,
        *range(0x2000, 0x200B), 0x2028, 0x2029, 0x202F, 0x205F, 0x3000,
    }
    got_ws = {cp for lo, hi in ws_runs for cp in range(lo, hi + 1)}
    assert got_ws == expected_ws, (len(got_ws), len(expected_ws))

    def emit(name: str, runs: list[tuple[int, int]]) -> str:
        rows, row = [], []
        for lo, hi in runs:
            row.append(f".{{ 0x{lo:X}, 0x{hi:X} }}")
            if len(row) == 4:
                rows.append("    " + ", ".join(row) + ",")
                row = []
        if row:
            rows.append("    " + ", ".join(row) + ",")
        body = "\n".join(rows)
        return f"pub const {name}: []const [2]u21 = &.{{\n{body}\n}};\n"

    zig = (
        "//! Generated by make_class_tables.py — DO NOT EDIT BY HAND.\n"
        f"//! Unicode {version} (Python unicodedata). isL = L*, isN = N* (Rust\n"
        "//! regex \\p{L}/\\p{N} semantics), isWs = the Unicode White_Space property\n"
        "//! (25 codepoints; deliberately NOT Python's str.isspace). Inclusive\n"
        "//! sorted ranges; lookup early-exits linearly.\n"
        f'pub const UNICODE_VERSION = "{version}";\n\n'
        + emit("l_ranges", l_runs)
        + "\n"
        + emit("n_ranges", n_runs)
        + "\n"
        + emit("ws_ranges", ws_runs)
    )
    OUT.write_text(zig)
    print(
        f"unicode {version} -> {OUT}\n"
        f"  L ranges={len(l_runs)}  N ranges={len(n_runs)}  ws ranges={len(ws_runs)}"
    )


if __name__ == "__main__":
    main()
